const swaggerJsdoc = require('swagger-jsdoc');

const options = {
    definition: {
        openapi: '3.0.0',
        info: {
            title: 'API RESTful for tasks (Node.js/Express/MongoDB)',
            version: '1.0.0',
            description: 'A complete API for task management with JWT authentication, designed for the portfolio.',
        },
        components: {
            securitySchemes: {
                bearerAuth: {
                    type: 'http',
                    scheme: 'bearer',
                    bearerFormat: 'JWT',
                },
            },
            schemas: {
                Task: {
                    type: 'object',
                    properties: {
                        _id: {
                            type: 'string',
                            description: 'ID generated by MongoDB'
                        },
                        user: {
                            type: 'string',
                            description: 'ID of the user who owns the task'
                        },
                        title: {
                            type: 'string',
                            description: 'Title of the task'
                        },
                        description: {
                            type: 'string',
                            description: 'Description of the task'
                        },
                        completed: {
                            type: 'boolean',
                            description: 'Status of the task'
                        },
                        createdAt: {
                            type: 'string',
                            format: 'date-time'
                        },
                        updatedAt: {
                            type: 'string',
                            format: 'date-time'
                        }
                    }
                }
            }
        },
        security: [
            {
                bearerAuth: [],
            },
        ],
        servers: [
            {
                url: `https://task-api-mern-portfolio.onrender.com/api`, 
                description: 'Production Server on Render'
            },
            {
                url: `http://localhost:${process.env.PORT || 4000}/api`,
                description: 'Local Development Server',
            },
        ],
    },
    apis: ['./src/routes/*.js', './src/controllers/*.js'], 
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = swaggerSpec;